# Generated by Django 4.0.2 on 2022-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Dr', 'Draft'), ('OK', 'Signed'), ('SC', 'Send to customer')], default='Dr', max_length=2),
        ),
    ]
