# Generated by Django 4.0.2 on 2022-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('SC', 'Send to customer'), ('Dr', 'Draft'), ('OK', 'Signed')], default='Dr', max_length=2),
        ),
    ]
