# Generated by Django 4.0.2 on 2022-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='medium',
            field=models.CharField(choices=[('SN', 'Social Network'), ('FA', 'Fair'), ('eM', 'Email'), ('pM', 'Postal Mail'), ('PH', 'Phoning')], max_length=2),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='validate_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
