# Generated by Django 4.0.2 on 2022-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='medium',
            field=models.CharField(choices=[('pM', 'Postal Mail'), ('SN', 'Social Network'), ('PH', 'Phoning'), ('eM', 'Email'), ('FA', 'Fair')], max_length=2),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='validate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
