# Generated by Django 4.0.2 on 2022-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_alter_conversion_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='medium',
            field=models.CharField(choices=[('pM', 'Postal Mail'), ('FA', 'Fair'), ('PH', 'Phoning'), ('SN', 'Social Network'), ('eM', 'Email')], max_length=2),
        ),
    ]
