# Generated by Django 4.0.2 on 2022-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_alter_conversion_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='medium',
            field=models.CharField(choices=[('PH', 'Phoning'), ('FA', 'Fair'), ('SN', 'Social Network'), ('pM', 'Postal Mail'), ('eM', 'Email')], max_length=2),
        ),
    ]
