# Generated by Django 4.0.2 on 2022-03-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('acti', 'Active'), ('anon', 'Anonymized')], max_length=4)),
                ('mailing_address', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('LI', 'Linkedin')], max_length=2)),
                ('username', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name_plural': 'Networks',
            },
        ),
    ]
