# Generated by Django 4.0.2 on 2022-02-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('acti', 'Active'), ('lead', 'Lead'), ('anon', 'Anonymized')], max_length=4),
        ),
    ]
