# Generated by Django 4.0.2 on 2022-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('acti', 'Active'), ('anon', 'Anonymized'), ('lead', 'Lead')], max_length=4),
        ),
        migrations.AlterField(
            model_name='networks',
            name='name',
            field=models.CharField(choices=[('LI', 'Linkedin'), ('FB', 'Facebook'), ('TW', 'Twitter')], max_length=2),
        ),
    ]
