# Generated by Django 4.0.2 on 2022-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_status_alter_networks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='name',
            field=models.CharField(choices=[('FB', 'Facebook'), ('LI', 'Linkedin'), ('TW', 'Twitter')], max_length=2),
        ),
    ]
