# Generated by Django 4.0.2 on 2022-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('anon', 'Anonymized'), ('lead', 'Lead'), ('acti', 'Active')], max_length=4),
        ),
        migrations.AlterField(
            model_name='networks',
            name='name',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'Linkedin')], max_length=2),
        ),
    ]
